# Generated by Django 4.0.4 on 2022-06-01 03:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Websitebank', '0002_alter_account_user_pin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account_user',
            managers=[
                ('user_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
