# Generated by Django 4.0.4 on 2022-06-04 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Websitebank', '0006_remove_profile_id_alter_profile_card_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receiver_no', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('notes', models.CharField(max_length=100)),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
