# Generated by Django 4.0.4 on 2022-06-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Websitebank', '0011_alter_profilepic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='image',
            field=models.ImageField(default=None, upload_to='profile_pics'),
        ),
    ]
