# Generated by Django 4.0.4 on 2022-06-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Websitebank', '0013_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
